Integrate CodeX Interactive Assembly Environment into ROM
commanderx16/x16-rom pull request #202
Opened 2021-04-12 15:39 UTC by mjallison42

First integration of the CodeX Interactive Assembly Environment into ROM. There are likely to be future bug fixes, etc.

2021-04-12 17:46 UTC, mist64 requested changes
Great. Just one issue; and consider changing to TABs instead of spaces (and no TAB/spaces between mnemonic and operand?) for consistency with the majority of the source in this repo. But as mentioned to you privately before, this is entirely your choice, since it's a pretty much standalone sub-project. I just suggest it so future edits by different people are less likely to completely mess up the formatting.

2021-04-12 17:46 UTC, mist64 commented on basic/token2.s
> +	.byt "C", 'X' + $80
can you move the new keyword to the end of the list, so the tokens are not renumbered? otherwise, this would break all BASIC programs SAVEd.

2021-04-12 18:45 UTC, mjallison42 commented on basic/token2.s
> +	.byt "C", 'X' + $80
e.g. move after BIN$ ?

2022-03-21 06:40 UTC, merged

2022-03-31 09:51 UTC, tomxp411 commented
This seems to be failing on the R39 emulator, as per 

https://www.commanderx16.com/forum/index.php?/topic/2585-codex/

2022-03-31 15:15 UTC, mjallison42 commented
I will be submitting a PR next week with a series of fixes.

Mike A 

> On Mar 31, 2022, at 2:51 AM, Tom Wilson ***@***.***> wrote:
> 
> 
> This seems to be failing on the R39 emulator, as per
> 
> https://www.commanderx16.com/forum/index.php?/topic/2585-codex/ <https://www.commanderx16.com/forum/index.php?/topic/2585-codex/>
> —
> Reply to this email directly, view it on GitHub <https://github.com/commanderx16/x16-rom/pull/202#issuecomment-1084346917>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/APALHJPDAY6GHSFNMSDZOYDVCVYSNANCNFSM42ZRKHCA>.
> You are receiving this because you authored the thread.
>